### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by lachenmayer** [jprichardson/buffer-json#2]
Hi JP, I've been using this library in a project and noticed that it crashes when keys are undefined, as can be seen in [this Runkit](https://runkit.com/embed/kngtkatvha5k).

```js
var bufferJson = require("buffer-json")
JSON.stringify({ohNo: undefined}, bufferJson.replacer)
// => TypeError: Cannot read property 'type' of undefined
```

This is the same bug that caused PR #1.

Because I needed to make progress, I forked the project & fixed the bug - I noticed that the module is quite outdated now, so it resulted in a complete rewrite (ie. it is currently using the deprecated Buffer constructor, deprecated mocha methods etc.): https://github.com/lachenmayer/buffer-json

I'm happy to use the fork namespaced under my name for now ([@lachenmayer/buffer-json](https://www.npmjs.com/package/@lachenmayer/buffer-json)), but it might be useful to others too. I also made the documentation a bit clearer & removed all the references to Node 0.10, as they're not really relevant anymore.

I haven't opened a PR for this, as I'm not sure if you want to keep maintaining this module and merge in the changes, or if it would be more useful transfer ownership and/or mark this repo as deprecated. Let me know what works for you.

Thanks a lot!

**Comment by jprichardson** [comment]
@lachenmayer your implementation looks good. 

Please make the following changes:

1. keep the `fixtures` file (rename to `.js`)
2. add your new tests to the fixtures file

(using Tape is fine)

Submit a PR and I'll make it happen. Thanks.

**Comment by mistic** [comment]
@jprichardson I think we can close that issue as the PR https://github.com/jprichardson/buffer-json/pull/3 was merged
